version: '3.7'

networks:
  elastic_net:
    driver: bridge
    attachable: true

volumes:
  elastic_data:

services:
  elastic0801:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    environment:
      - xpack.security.enabled=false
      # - cluster.name=es-docker-cluster
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - elastic_net
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == my-host]

  kibana08:
    image: docker.elastic.co/kibana/kibana:8.11.3
    environment:
      # - node.name=kib8
      # - cluster.name=es-docker-cluster
      - ELASTICSEARCH_HOSTS=http://elastic0801:9200
      # - ELASTICSEARCH_USERNAME=elastic
      # - ELASTICSEARCH_PASSWORD=changeme
      # - XPACK_SECURITY_ENABLED=true
      # - XPACK_SECURITY_AUTH_PROVIDERS='readonlyrest_kbn'
      # - XPACK_SECURITY_READ_ONLY_REST_PLUGIN_USERNAME=kibana
      # - XPACK_SECURITY_READ_ONLY_REST_PLUGIN_PASSWORD=kibanapassword
    ports:
      - "5601:5601"
    networks:
      - elastic_net
    depends_on:
      - elastic0801
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == my-host]
